### PR TITLE
Better space handling ?

### PR DESCRIPTION
**Pull request by benoitkugler**
Following the discussion on #90 , this is a try at better handling trailing spaces.

This is not complete (tests are not event passing), but I would be interested in early feedback.

One of the difficulty is about handling truncation properly :
I think the behavior should be, for a width of 5, to truncate
`quick_fox`
to 
`quick_...` (but with a zero advance space)
and not to 
`quick...`

### CODE REVIEW

**Review by whereswaldon — COMMENTED** [review]
Thank you for tackling this! I think this approach is sound conceptually, and I agree that it's best to keep trailing zero-width space at the end of lines than to push it to the start of new lines.

We should eventually handle the case of multiple consecutive whitespaces at the end of a run, but I think it's reasonable to start with just one.

I was surprised that we're detecting whitespace purely based on whether the Width/Height fields of the glyph metadata are zero. In practice, I suppose that should be effective. I just expected something fancier.

**Comment by benoitkugler** [comment]
@whereswaldon I've adjusted some tests in `TestLineWrapperBreakSpecific`. I think the new output values are fine, but I also think some of the tests may not be as informative as previously, with respect to the `BreakPolicy` option. When you have some time, would it be possible for you to carefully review these changes ?

**Comment by whereswaldon** [comment]
> @whereswaldon I've adjusted some tests in `TestLineWrapperBreakSpecific`. I think the new output values are fine, but I also think some of the tests may not be as informative as previously, with respect to the `BreakPolicy` option. When you have some time, would it be possible for you to carefully review these changes ?

@benoitkugler Done! I've fixed up two tests to ensure that they still check the right things. Looks good to me now.

**Comment by benoitkugler** [comment]
> @benoitkugler Done! I've fixed up two tests to ensure that they still check the right things. Looks good to me now.

Many thanks !

**Review by whereswaldon — APPROVED** [review]
Thanks for tackling this important feature! It's a big deal for centering and right-aligning LTR text.

**Comment by andydotxyz** [comment]
Looks great. Wish I had time to test replacing our white space / align code from Fyne but I have other open PRs that clash at the moment.

**Review by andydotxyz — APPROVED** [review]
Looks great. Wish I had time to test replacing our white space / align code from Fyne but I have other open PRs that clash at the moment.

**Pull request merged**
