### PR TITLE
opentype, fontscan: remove go1.16 build constraints

### PR DESCRIPTION
**Pull request by hajimehoshi**
Now this project uses Go 1.17 and newer, an old code for Go 1.15 and older should not be needed.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
I assumed this project assumpts Go 1.17 from go.mod, but perhaps do we need to test this with Go 1.14?

**Comment by benoitkugler** [comment]
Thank you for this contribution.

> I assumed this project uses Go 1.17 from go.mod, but perhaps do we need to test this with Go 1.14?

It was indeed the case, but now that Fyne has bumped its minimum version, I think it should be OK. 
Cc @andydotxyz for confirmation

**Review by andydotxyz — APPROVED** [review]
Looks like a good catch thanks

**Review by benoitkugler — APPROVED** [review]
Nice clean up !

**Pull request merged**
