### PR TITLE
Proposing review guidelines

### PR DESCRIPTION
**Pull request by andydotxyz**
As discussed in passing - this should help to speed up smaller changes.

### CODE REVIEW

**Review by benoitkugler — APPROVED** [review]
Nice proposal, thank you ! 

Just a question : we will update the github protection rules to reduce the number of required owner reviews to one for all PRs, right ?

**Review by whereswaldon — APPROVED** [review]
Works for me. We will have to change the PR policy to only strictly require 1 approval in order for the smaller changes portion to work, but I'm not worried about our ability to respect the policy.

**Comment by whereswaldon** [comment]
I have updated the branch protection rule to only *require* one code owner review.

**Comment by andydotxyz** [comment]
Thanks so much :) yes it will require a little care to keep the policy respected but I'm sure we can manage appropriately.

**Pull request merged**
