### PR TITLE
Fix variations parsing

### PR DESCRIPTION
**Pull request by benoitkugler**
I've discovered a bug when trying to load a corrupted (subsetted) font file. The issue is that we can't really trust the count of point numbers found in the 'glyf' table. 
This commit adds a check to avoid out of bounds crashes.

### CODE REVIEW

**Review by whereswaldon — APPROVED** [review]

**Comment by whereswaldon** [comment]
I wouldn't complain about adding a regression test for this, but I won't require it.

**Review by andydotxyz — APPROVED** [review]
Likewise

**Comment by benoitkugler** [comment]
Test added !

**Review by andydotxyz — APPROVED** [review]
Thanks

**Pull request merged**
