### PR TITLE
Optimize familyCrible creation

### PR DESCRIPTION
**Pull request by egonelbre**
Generally speaking `container/list` is usually not the best choice for constructing things. This replaces that list/container with a regular slice and gets a significant performance win.

There probably is a block linked list or rope like structure that would probably work even better.

### CODE REVIEW

**Comment by egonelbre** [comment]
I'm not quite sure, but what's the minimum version this package should support?

**Comment by whereswaldon** [comment]
> I'm not quite sure, but what's the minimum version this package should support?

We are limited to supporting the oldest version of Go that Fyne supports. That was Go 1.14, but *may* be Go 1.17 now. @andydotxyz, did that transition already happen? Either way, we unfortunately cannot use generics.

**Comment by egonelbre** [comment]
@whereswaldon ok, I created non-generic funcs of them

**Comment by benoitkugler** [comment]
Could you provide some benchmark or evidence that this is actually a performance gain? Thank you!

**Comment by egonelbre** [comment]
The second commit contained the benchmark:

```
  goos: windows
  goarch: amd64
  pkg: github.com/go-text/typesetting/fontscan
  cpu: AMD Ryzen Threadripper 2950X 16-Core Processor
                                │  base~.log  │             slice~.log              │
                                │   sec/op    │   sec/op     vs base                │
  ResolveFont-32                  21.57µ ± 2%   21.91µ ± 4%   +1.55% (p=0.035 n=10)
  SetQuery-32                     53.06n ± 2%   52.75n ± 3%        ~ (p=1.000 n=10)
  NewFamilyCrible-32              40.83µ ± 1%   21.96µ ± 1%  -46.22% (p=0.000 n=10)
  ScriptSet/naive-32              112.1m ± 1%   106.0m ± 1%   -5.46% (p=0.000 n=10)
  ScriptSet/from_rune_pages-32    4.140m ± 6%   3.894m ± 1%   -5.94% (p=0.000 n=10)
  ScriptSet/from_rune_ranges-32   1.767m ± 1%   1.727m ± 1%   -2.27% (p=0.000 n=10)
  ScanFonts-32                    430.1m ± 3%   427.4m ± 2%        ~ (p=0.579 n=10)
  geomean                         556.3µ        499.2µ       -10.26%
```

But, did you mean something additional to it?

**Comment by benoitkugler** [comment]
> The second commit contained the benchmark:
> 
> ```
>   goos: windows
>   goarch: amd64
>   pkg: github.com/go-text/typesetting/fontscan
>   cpu: AMD Ryzen Threadripper 2950X 16-Core Processor
>                                 │  base~.log  │             slice~.log              │
>                                 │   sec/op    │   sec/op     vs base                │
>   ResolveFont-32                  21.57µ ± 2%   21.91µ ± 4%   +1.55% (p=0.035 n=10)
>   SetQuery-32                     53.06n ± 2%   52.75n ± 3%        ~ (p=1.000 n=10)
>   NewFamilyCrible-32              40.83µ ± 1%   21.96µ ± 1%  -46.22% (p=0.000 n=10)
>   ScriptSet/naive-32              112.1m ± 1%   106.0m ± 1%   -5.46% (p=0.000 n=10)
>   ScriptSet/from_rune_pages-32    4.140m ± 6%   3.894m ± 1%   -5.94% (p=0.000 n=10)
>   ScriptSet/from_rune_ranges-32   1.767m ± 1%   1.727m ± 1%   -2.27% (p=0.000 n=10)
>   ScanFonts-32                    430.1m ± 3%   427.4m ± 2%        ~ (p=0.579 n=10)
>   geomean                         556.3µ        499.2µ       -10.26%
> ```
> 
> But, did you mean something additional to it?

I've missed that, sorry. Sounds good to me then, thank you !

**Review by benoitkugler — APPROVED** [review]

**Comment by andydotxyz** [comment]
> > I'm not quite sure, but what's the minimum version this package should support?
> 
> We are limited to supporting the oldest version of Go that Fyne supports. That was Go 1.14, but _may_ be Go 1.17 now. @andydotxyz, did that transition already happen? Either way, we unfortunately cannot use generics.

Yes, we released the update to require Go 1.17 just 2 days ago :)

**Review by andydotxyz — COMMENTED** [review]
This looks good, but should there not be tests for the 2 new methods that replace List methods?

**Comment by egonelbre** [comment]
> This looks good, but should there not be tests for the 2 new methods that replace List methods?

I can add them, but I was partly hoping that they will be replaced by `slices.*`, so there wouldn't be a need to maintain them. Is there a timeline for fyne upgrading to 1.18? But, if not then I can add some tests.

**Comment by egonelbre** [comment]
@andydotxyz, I added tests, and of course, found a bug :)

**Comment by andydotxyz** [comment]
> Is there a timeline for fyne upgrading to 1.18? But, if not then I can add some tests.

We are discussing moving to 1.19 in the next major release - no ETA yet but I would guess January '24.

**Review by andydotxyz — APPROVED** [review]
Nice :)

**Review by whereswaldon — APPROVED** [review]
Looks good to me. Ran the tests here an in Gio atop this change, tried it out. Everything seems good. Thanks @egonelbre!

**Pull request merged**
