### PR TITLE
Merge all repos with history

### PR DESCRIPTION
**Pull request by whereswaldon**
Supersedes #1 

This should be essentially the same changes as #1, but with the full git history attached. Please take a peek and let me know if anything seems incorrect.

### CODE REVIEW

**Review by andydotxyz — APPROVED** [review]
Nice tidyup too :) thanks

**Comment by benoitkugler** [comment]
Very nice, thanks !

**Comment by andydotxyz** [comment]
> Can me merge this ?

I don't think there should be any hold-up

**Comment by whereswaldon** [comment]
I've removed the redundant license and am merging now.

**Pull request merged**
